# Generated by Django 2.2.5 on 2019-09-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='books.BookItem'),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='authorr',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.Author'),
        ),
    ]
