# Generated by Django 2.2.5 on 2019-09-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='zip_code',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
