# Generated by Django 2.2.5 on 2019-09-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20190930_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'SUCCESS'), ('F', 'FAILED')], max_length=1, null=True),
        ),
    ]
